In [1]:
print("Hi there")

Hi there

In [2]:
%pip install -r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt

Requirement already satisfied: pandas in c:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\venv\Lib\site-packages (from -r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\venv\Lib\site-packages (from pandas->-r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt (line 1)) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\behur\AppData\Roaming\Python\Python313\site-packages (from pandas->-r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\venv\Lib\site-packages (from pandas->-r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt (line 1)) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\behur\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas->-r C:\Users\behur\OneDrive\Documents\Krish_naik_ai_agent\genai_bootcamp\requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [10]:
data=pd.read_csv("https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv")

In [5]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
data.sample(10)

                                                  review sentiment
12636  I saw this film with a special screening of th...  positive
16389  This movie was almost intolerable to sit throu...  negative
14013  This is truly one from the "Golden Age" of Hol...  positive
9147   This film is about the worst I have seen in a ...  negative
45698  There are so many holes in the plot, it makes ...  negative
26111  It's very easy to figure out why The New Profe...  positive
14333  I loved the original P.H. and was somewhat sat...  negative
16014  Predictable Unmotivated Pointless Caricatures ...  negative
4659   The line, of course, is from the Lord's Prayer...  positive
22592  Great actors, good filming, a potentially inte...  negative

In [6]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [10]:
data['review']=data['review'].str.lower()

In [11]:
text="""<!DOCTYPE html><html lang="en"><head><meta
charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta
name="viewport" content="width=device-width,
initial-scale=1.0"><title>Welcome to My
Website</title><style>body{font-family:'Arial',sans-serif;background-color
:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style
></head><body><header><h1>Welcome to My Awesome
Website!</h1></header><main><p>This is a sample HTML document created for
demonstration purposes.</p><p>Feel free to explore and enjoy the content
on this website.</p></main><footer><p>&copy; 2024 My Website. All rights
reserved.</p></footer></body></html>"""

In [14]:
import re
def remove_html_tag(text):
    pattern=re.compile('<.*?>')
    return pattern.sub("",text)

In [15]:
remove_html_tag(text)

'<meta\ncharset="UTF-8"><meta\nname="viewport" content="width=device-width,\ninitial-scale=1.0">Welcome to My\nWebsitebody{font-family:\'Arial\',sans-serif;background-color\n:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style\n>Welcome to My Awesome\nWebsite!This is a sample HTML document created for\ndemonstration purposes.Feel free to explore and enjoy the content\non this website.&copy; 2024 My Website. All rights\nreserved.'

In [16]:
import string

In [21]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
text="string @ *() with punctuation.!"

In [13]:
def remove_punch(text):
    for char in text:
        text=text.replace(char,"")

In [14]:
data["review"]=data["review"].apply(remove_punch)